### ISSUE TITLE
Render method is not being called inside step, so no visualizations happen

### ISSUE THREAD

**Issue by ChristoferBerruz** [sjsu-interconnect/ourhexgame#36]
Although we have implemented the render method, we are not calling inside the step method. Therefore, no rendering is happening. I believe we should be calling render inside step as to see the progress of the game

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the step method in the OurHexGame class to call the render method after each move, allowing the game progress to be visualized.

You can review changes in this commit: https://github.com/lattaai13/sjsu-interconnect-ourhexgame-36/commit/4bdf5ac11551b876e178050035d36742c0aba53c.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by S-GargHub** [comment]
Added the call to the render method if the render mode is human. If render_mode is None, no rendering will happen.
