### ISSUE TITLE
Return a copy of the board in the observe method

### ISSUE THREAD

**Issue by ChristoferBerruz** [sjsu-interconnect/ourhexgame#41]
We are only returning the `self.board` using the `observe` method.

This is a bug in the environment. Why? Assume the agent holds the observation from the **first** step.
In the third step, the observation from the first step (held by the agent) will mutate
to reflect the state of the board at the third step. This is undesired behavior.

The fix will be to return a simple `.copy` version of the board in the `observe` method

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the observe method in the OurHexGame class to return a copy of the board instead of the original reference. This prevents unintended mutations of the observation held by the agent across different steps.

You can review changes in this commit: https://github.com/lkilu6456546/sjsu-interconnect-ourhexgame-41/commit/8df0dbdcd3da4e11be530b392f143183adbbef65.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
